In [168]:
library(dplyr)
library(stringr)

In [178]:
apartment_data = read.csv('./train.csv')
apartment_data =data.frame(apartment_data)
head(apartment_data)
tail(apartment_data)
apratment_data = apartment_data[apartment_data$city =='서울특별시',] # 서울특별시 자료만 추출
apartment_data=apartment_data[-1,-2,-3,-5,-6,-7,-8,-9,-10,-11,-12]
apartment_data

  transaction_id apartment_id city       dong   jibun  apt
1 0               7622        서울특별시 신교동 6-13   신현(101동)
2 1               5399        서울특별시 필운동 142    사직파크맨션
3 2               3578        서울특별시 필운동 174-1  두레엘리시안
4 3              10957        서울특별시 내수동 95     파크팰리스
5 4              10639        서울특별시 내수동 110-15 킹스매너
6 5              12536        서울특별시 인의동 48-2   효성쥬얼리시티
  addr_kr                    exclusive_use_area year_of_completion
1 신교동 6-13 신현(101동)     84.82             2002
2 필운동 142 사직파크맨션     99.17             1973
3 필운동 174-1 두레엘리시안   84.74             2007
4 내수동 95 파크팰리스       146.39             2003
5 내수동 110-15 킹스매너     194.43             2004
6 인의동 48-2 효성쥬얼리시티 106.81             2006
  transaction_year_month transaction_date floor transaction_real_price
1 200801                 21~31             2     37500
2 200801                 1~10              6     20000
3 200801                 1~10              6     38500
4 200801                 11~20            15    118000
5 200801                 21~31             3    120000
6 200801                 1~10             16     67000

        transaction_id apartment_id city       dong          jibun
1216548 1234822        9587         부산광역시 정관읍 용수리 1403
1216549 1234823        9578         부산광역시 정관읍 용수리 1387
1216550 1234824        9578         부산광역시 정관읍 용수리 1387
1216551 1234825        9578         부산광역시 정관읍 용수리 1387
1216552 1234826        9586         부산광역시 정관읍 용수리 1364
1216553 1234827        9578         부산광역시 정관읍 용수리 1387
        apt                  addr_kr
1216548 정관신도시한진해모로 정관읍 용수리 1403 정관신도시한진해모로
1216549 정관 동일스위트1차   정관읍 용수리 1387 정관 동일스위트1차
1216550 정관 동일스위트1차   정관읍 용수리 1387 정관 동일스위트1차
1216551 정관 동일스위트1차   정관읍 용수리 1387 정관 동일스위트1차
1216552 정관신도시롯데캐슬   정관읍 용수리 1364 정관신도시롯데캐슬
1216553 정관 동일스위트1차   정관읍 용수리 1387 정관 동일스위트1차
        exclusive_use_area year_of_completion transaction_year_month
1216548 109.3076           2008               201711
1216549  59.8245           2012               201711
1216550  84.9923           2012               201711
1216551  84.9923           2012               201711
1216552 101.7400           2008               201711
1216553  84.9923           2012               201711
        transaction_date floor transaction_real_price
1216548 11~20             5    36000
1216549 11~20             3    22000
1216550 21~30             7    30750
1216551 21~30             9    29500
1216552 21~30             7    26700
1216553 21~30            16    28800

ERROR: Error in `[.data.frame`(apartment_data, -1, -2, -3, -5, -6, -7, -8, -9, : unused arguments (-5, -6, -7, -8, -9, -10, -11, -12)

In [180]:
apartment_data[1]

        transaction_id
1        0
2        1
3        2
4        3
5        4
6        5
7        6
8        7
9        8
10       9
11      10
12      11
13      12
14      13
15      14
16      15
17      16
18      17
19      18
20      19
21      20
22      21
23      22
24      23
25      24
26      25
27      26
28      27
29      28
30      29
⋮       ⋮
1216524 1234798
1216525 1234799
1216526 1234800
1216527 1234801
1216528 1234802
1216529 1234803
1216530 1234804
1216531 1234805
1216532 1234806
1216533 1234807
1216534 1234808
1216535 1234809
1216536 1234810
1216537 1234811
1216538 1234812
1216539 1234813
1216540 1234814
1216541 1234815
1216542 1234816
1216543 1234817
1216544 1234818
1216545 1234819
1216546 1234820
1216547 1234821
1216548 1234822
1216549 1234823
1216550 1234824
1216551 1234825
1216552 1234826
1216553 1234827

In [170]:
subway_data = read.csv('./subway.csv',header = T, fileEncoding = "euc-kr")
head(subway_data)
tail(subway_data)

  호선  역명    구주소
1 2호선 봉천    서울특별시 관악구 봉천동 979-7 봉천역(2호선)
2 1호선 서울    서울특별시 중구 남대문로5가 73-6 서울역(1호선)
3 1호선 시청    서울특별시 중구 정동 5-5 시청역(1호선)
4 1호선 종각    서울특별시 종로구 종로1가 54 종각역(1호선)
5 1호선 종로3가 서울특별시 종로구 종로3가 10-5 종로3가역(1호선)
6 1호선 종로5가 서울특별시 종로구 종로5가 82-1 종로5가역(1호선)
  도로명주소                                    전화번호
1 서울특별시 관악구 남부순환로 지하1721(봉천동) 02-6110-2291
2 서울특별시 중구 세종대로 지하2(남대문로 5가)  02-6110-1331
3 서울특별시 중구 세종대로 지하101(정동)        02-6110-1321
4 서울특별시 종로구 종로 지하55(종로1가)        02-6110-1311
5 서울특별시 종로구 종로 지하129(종로3가)       02-6110-1301
6 서울특별시 종로구 종로 지하216(종로5가)       02-6110-1291

    호선  역명
283 9호선 석촌
284 9호선 송파나루
285 9호선 한성백제
286 9호선 올림픽공원(한국체대)
287 9호선 둔촌오륜
288 9호선 중앙보훈병원
    구주소
283 서울특별시 송파구 석촌동 209 석촌역(9호선)
284 서울특별시 송파구 방이동 2 송파나루역(9호선)
285 서울특별시 송파구 방이동 88-17 한성백제역(9호선)
286 서울특별시 송파구 방이동 89-28 올림픽공원역(9호선)
287 서울특별시 강동구 둔촌동 227-7 둔촌오륜역(9호선)
288 서울특별시 강동구 둔촌동 8-1 중앙보훈병원역(9호선)
    도로명주소                                   전화번호
283 서울특별시 송파구 송파대로 지하439(석촌동)   02-2656-0933
284 서울특별시 송파구 백제고분로 지하446(방이동) 02-2656-0934
285 서울특별시 송파구 위례성대로 지하29(방이동)  02-2656-0935
286 서울특별시 송파구 양재대로 지하1233(방이동)  02-2656-0936
287 서울특별시 강동구 강동대로 지하303(둔촌동)   02-2656-0937
288 서울특별시 강동구 동남로 지하625(둔촌동)     02-2656-0938

In [171]:
subway_data=subway_data[-4] #불필요한 컬럼(도로명 주소, 역사 전화번호) 삭제.
subway_data=subway_data[-4] #불필요한 컬럼(도로명 주소, 역사 전화번호) 삭제.
subway_data

    호선  역명
1   2호선 봉천
2   1호선 서울
3   1호선 시청
4   1호선 종각
5   1호선 종로3가
6   1호선 종로5가
7   1호선 동대문
8   1호선 신설동
9   1호선 제기동
10  1호선 청량리(서울시립대입구)
11  1호선 동묘앞
12  2호선 시청
13  2호선 을지로입구
14  2호선 을지로3가
15  2호선 을지로4가
16  2호선 동대문역사문화공원(DDP)
17  2호선 신당
18  2호선 상왕십리
19  2호선 왕십리(성동구청)
20  2호선 한양대
21  2호선 뚝섬
22  2호선 성수
23  2호선 건대입구
24  2호선 구의(광진구청)
25  2호선 강변(동서울터미널)
26  2호선 잠실나루
27  2호선 잠실(송파구청)
28  2호선 잠실새내
29  2호선 종합운동장
30  2호선 삼성(무역센터)
⋮   ⋮     ⋮
259 8호선 천호(풍납토성)
260 8호선 강동구청
261 8호선 몽촌토성(평화의문)
262 8호선 잠실(송파구청)
263 8호선 석촌
264 8호선 송파
265 8호선 가락시장
266 8호선 문정
267 8호선 장지
268 8호선 복정
269 8호선 남위례
270 8호선 산성
271 8호선 남한산성입구(성남법원?검찰청)
272 8호선 단대오거리
273 8호선 신흥
274 8호선 수진
275 8호선 모란
276 9호선 언주
277 9호선 선정릉
278 9호선 삼성중앙
279 9호선 봉은사
280 9호선 종합운동장
281 9호선 삼전
282 9호선 석촌고분
283 9호선 석촌
284 9호선 송파나루
285 9호선 한성백제
286 9호선 올림픽공원(한국체대)
287 9호선 둔촌오륜
288 9호선 중앙보훈병원
    구주소
1   서울특별시 관악구 봉천동 979-7 봉천역(2호선)
2   서울특별시 중구 남대문로5가 73-6 서울역(1호선)
3   서울특별시 중구 정동 5-5 시청역(1호선)
4   서울특별시 종로구 종로1가 54 종각역(1호선)
5   서울특별시 종로구 종로3가 10-5 종로3가역(1호선)
6   서울특별시 종로구 종로5가 82-1 종로5가역(1호선)
7   서울특별시 종로구 창신동 492-1 동대문역(1호선)
8   서울특별시 동대문구 신설동 76-5 신설동역(1호선)
9   서울특별시 동대문구 제기동 65 제기동역(1호선)
10  서울특별시 동대문구 전농동 620-69 청량리역(1호선)
11  서울특별시 종로구 숭인동 117 동묘앞역(1호선)
12  서울특별시 중구 서소문동 90-1 시청역(2호선)
13  서울특별시 중구 을지로1가 100-1 을지로입구역(2호선)
14  서울특별시 중구 을지로3가 347-3 을지로3가역(2호선)
15  서울특별시 중구 을지로4가 267-1 을지로4가역(2호선)
16  서울특별시 중구 을지로 7가 112-3 동대문역사문화공원역(2호선)
17  서울특별시 중구 신당동 99 신당역(2호선)
18  서울특별시 성동구 하왕십리동 946-14 상왕십리역(2호선)
19  서울특별시 성동구 행당동 192 왕십리역(2호선)
20  서울특별시 성동구 행당동 산17 한양대역(2호선)
21  서울특별시 성동구 성수동1가 656-745 뚝섬역(2호선)
22  서울특별시 성동구 성수동2가 300-1 성수역(2호선)
23  서울특별시 광진구 화양동 7-3 2호선 건대입구역(2호선)
24  서울특별시 광진구 구의동 245-24 구의역(2호선)
25  서울특별시 광진구 구의동 546-6 강변역(2호선)
26  서울특별시 송파구 신천동 15 잠실나루역(2호선)
27  서울특별시 송파구 신천동 8 잠실역(2호선)
28  서울특별시 송파구 잠실동 33 잠실새내역(2호선)
29  서울특별시 송파구 잠실동 122 종합운동장역(2호선)
30  서울특별시 강남구 삼성동 172-66 삼성역(2호선)
⋮   ⋮
259 서울특별시 강동구 천호동 455 천호역(8호선)
260 서울특별시 강동구 성내동 319 강동구청역(8호선)
261 서울특별시 송파구 신천동 19 몽촌토성역(8호선)
262 서울특별시 송파구 신천동 7-4 잠실역(8호선)
263 서울특별시 송파구 석촌동 209 석촌역(8호선)
264 서울특별시 송파구 가락동 459-4 송파역(8호선)
265 서울특별시 송파구 가락동 184-23 가락시장역(8호선)
266 서울특별시 송파구 문정동 119-4 문정역(8호선)
267 서울특별시 송파구 장지동 201-5 장지역(8호선)
268 서울특별시 송파구 장지동 596-21 복정역(8호선)
269 경기도 성남시 수정구 복정동 57 남위례역(8호선)
270 경기도 성남시 수정구 신흥동 7 산성역(8호선)
271 경기도 성남시 수정구 단대동 96 남한산성입구역(8호선)
272 경기도 성남시 수정구 신흥동 2467 단대오거리역(8호선)
273 경기도 성남시 수정구 신흥동 2467 신흥역(8호선)
274 경기도 성남시 수정구 수진동 2205-1 수진역(8호선)
275 경기도 성남시 수정구 수진동 4518 모란역(8호선)
276 서울특별시 강남구 논현동 279-165 언주역(9호선)
277 서울특별시 강남구 삼성동 111-114 선정릉역(9호선)
278 서울특별시 강남구 삼성동 111-147 삼성중앙역(9호선)
279 서울특별시 강남구 삼성동 172 봉은사역(9호선)
280 서울특별시 송파구 잠실동 123 종합운동장역(9호선)
281 서울특별시 송파구 잠실동 347 삼전역(9호선)
282 서울특별시 송파구 삼전동 157-1 석촌고분역(9호선)
283 서울특별시 송파구 석촌동 209 석촌역(9호선)
284 서울특별시 송파구 방이동 2 송파나루역(9호선)
285 서울특별시 송파구 방이동 88-17 한성백제역(9호선)
286 서울특별시 송파구 방이동 89-28 올림픽공원역(9호선)
287 서울특별시 강동구 둔촌동 227-7 둔촌오륜역(9호선)
288 서울특별시 강동구 둔촌동 8-1 중앙보훈병원역(9호선)

In [175]:
tmp_subway_data = str_split(subway_data$구주소," ",simplify=TRUE)  # 구주소를 띄어쓰기 단위로 분리
tmp_subway_data = data.frame(tmp_subway_data) #분리된 구 주소를 데이터프레임으로 변경 
dong_vec = c(tmp_subway_data$X3) # 동정보(X3열)를 벡터에 저장 
line_vec = c(subway_data$호선) # 호선 정보를 벡터에 저장
line_dong = cbind(line_vec,dong_vec) # 두개의 벡터를 결합
line_dong
dong_df = data.frame(table(dong_vec))

      line_vec dong_vec
 [1,] 2호선    봉천동
 [2,] 1호선    남대문로5가
 [3,] 1호선    정동
 [4,] 1호선    종로1가
 [5,] 1호선    종로3가
 [6,] 1호선    종로5가
 [7,] 1호선    창신동
 [8,] 1호선    신설동
 [9,] 1호선    제기동
[10,] 1호선    전농동
[11,] 1호선    숭인동
[12,] 2호선    서소문동
[13,] 2호선    을지로1가
[14,] 2호선    을지로3가
[15,] 2호선    을지로4가
[16,] 2호선    을지로
[17,] 2호선    신당동
[18,] 2호선    하왕십리동
[19,] 2호선    행당동
[20,] 2호선    행당동
[21,] 2호선    성수동1가
[22,] 2호선    성수동2가
[23,] 2호선    화양동
[24,] 2호선    구의동
[25,] 2호선    구의동
[26,] 2호선    신천동
[27,] 2호선    신천동
[28,] 2호선    잠실동
[29,] 2호선    잠실동
[30,] 2호선    삼성동
[31,] ⋮        ⋮
[32,] 8호선    천호동
[33,] 8호선    성내동
[34,] 8호선    신천동
[35,] 8호선    신천동
[36,] 8호선    석촌동
[37,] 8호선    가락동
[38,] 8호선    가락동
[39,] 8호선    문정동
[40,] 8호선    장지동
[41,] 8호선    장지동
[42,] 8호선    수정구
[43,] 8호선    수정구
[44,] 8호선    수정구
[45,] 8호선    수정구
[46,] 8호선    수정구
[47,] 8호선    수정구
[48,] 8호선    수정구
[49,] 9호선    논현동
[50,] 9호선    삼성동
[51,] 9호선    삼성동
[52,] 9호선    삼성동
[53,] 9호선    잠실동
[54,] 9호선    잠실동
[55,] 9호선    삼전동
[56,] 9호선    석촌동
[57,] 9호선    방이동
[58,] 9호선    방이동
[59,] 9호선    방이동
[60,] 9호선    둔촌동
[61,] 9호선    둔촌동

In [176]:
dong_df

    dong_vec    Freq
1   가락동      5
2   가산동      1
3   갈월동      1
4   갈현동      2
5   거여동      1
6   고덕동      1
7   공덕동      2
8   공릉동      4
9   공항동      1
10  광명동      1
11  광장동      1
12  광희동1가   1
13  광희동2가   1
14  구로동      3
15  구산동      1
16  구의동      2
17  금호동2가   1
18  금호동4가   1
19  길동        1
20  길음동      1
21  남대문로5가 1
22  남창동      1
23  노고산동    1
24  녹번동      2
25  논현동      3
26  능동        3
27  당산동      1
28  당산동3가   2
29  대림동      1
30  대방동      2
⋮   ⋮           ⋮
143 중곡동      1
144 중화동      1
145 증산동      2
146 진관동      1
147 창동        2
148 창신동      2
149 창우동      1
150 창전동      1
151 천왕동      1
152 천호동      3
153 철산동      1
154 청담동      1
155 충무로2가   1
156 충정로3가   2
157 평동        1
158 필동2가     2
159 하계동      1
160 하왕십리동  1
161 하월곡동    1
162 한강로1가   2
163 한강로2가   1
164 한남동      1
165 합정동      1
166 행당동      4
167 현저동      1
168 홍제동      2
169 화곡동      3
170 화양동      3
171 효창동      1
172 흥인동      1